### PR TITLE
Update UnrealManagerBase.py

### PR DESCRIPTION
**Pull request by ki11roy**
Additional target configurations to have ability to build dedicated server. 
Documentation: https://docs.unrealengine.com/en-US/Programming/Development/BuildConfigurations/index.html

### CODE REVIEW

**Comment by ki11roy** [comment]
Haven't tested it properly, though seems right.

**Comment by adamrehn** [comment]
Thanks for suggesting this feature! After looking through the documentation and experimenting with UBT and UAT, I've devised a slightly less intrusive mechanism for supporting dedicated server targets in both the [ue4 build](https://adamrehn.com/docs/ue4cli/descriptor-commands/build) and [ue4 package](https://adamrehn.com/docs/ue4cli/descriptor-commands/package) commands that provides a bit more flexibility for users and a more natural fit with the existing way that ue4cli adapts to user-specified arguments. These changes are implemented in commits decaae4 and 27c2ab2 (live in ue4cli version 0.0.33) and can be used as follows:

```bash
# Builds the modules for the dedicated server
ue4 build Development Server
```

```bash
# Packages the dedicated server
ue4 package Shipping -server -noclient
```

The implementation in the `ue4 package` command provides users with the flexibility to build both the client and server, or one without the other, and automatically adapts the other UAT flags to suit.

**Comment by ki11roy** [comment]
Perfect, thank you!

**Comment by ki11roy** [comment]
Just one note, to build dedicated server, one needs an ue-engine image which has no ue4cli. Have you though of separating it into standalone image (and including into engine, for example)?

And another thing, I have tried building with BuildCookRun (see https://wiki.unrealengine.com/How_to_package_your_game_with_commands) and it seems that it doesn’t need ‘ue4 build’ step at all, just ‘ue4 package’.

**Comment by adamrehn** [comment]
In the earliest versions of ue4-docker there was an image that contained both a source build of the Engine and ue4cli, but I ended up removing this when I added support for using an Installed Build, since the overwhelming majority of CI use cases benefit from a smaller image containing an immutable Engine installation. I've seen some blog posts describing a way to add dedicated server support to Installed Builds by modifying the BuildGraph XML data, so I might investigate the feasibility of integrating that as an option in ue4-docker to avoid the need to use an enormous source build just for packaging dedicated servers.

Yes, the code example in my previous comment was just designed to illustrate the way that the `ue4 build` and `ue4-package` commands can now be used to build and package dedicated servers. In practice you would only ever use one command in any given situation, most likely `ue4 build` to test that your server's target configuration is working correctly, and `ue4 package` to actually build and package the dedicated server.

**Pull request closed without merging**
