### PR TITLE
Move extraArgs earlier

### LINKED ISSUE #35: -VS2019 Optional Argument needs to be earlier
Passing in the optional argument -VS2019 as per `ue4 package Development -VS2019` results in errors that VS2017 doesn't exist. Running RunUAT also produces this error unless -VS2019 is just after BuildPlugin arg but before the Plugin/Package paraments.

### PR DESCRIPTION
**Pull request by CanisHelix**
Due to UE4's RunUAT command-line parsing, fixes #35

### CODE REVIEW

**Review by TBBle — APPROVED** [review]

**Comment by jonpas** [comment]
This is a problematic solution:
```
ue4 package Development -VS2019
...
Parsing command line: BuildPlugin Development -Plugin=\\LOKI\Work\IDI\acre\unreal\acre-unreal-plugin\ACREUnreal.uplugin -Package=E:\IDI\acre\unreal\acre-unreal-plugin\dist
```

Before `Development -VS2019` was put at the end (could also be why `-VS2019` was ignored?).

**Comment by jonpas** [comment]
Ah I see, I am packaging a Plugin, which doesn't really take configuration. Documentation isn't the most clear on that, I should have just done `$ ue4 package -VS2019`. Not sure if it's better to streamline it for both or add a line in documentation saying configuration parameter should be ignored for plugins (probably better).

**Comment by CanisHelix** [comment]
That caught me out a few times at first too. Glad you figured it out.

**Comment by adamrehn** [comment]
@CanisHelix thanks for your contribution! Apologies for taking so long to take a look at this, the lead-up to the release of Unreal Engine 4.27 was super hectic.

**Comment by adamrehn** [comment]
Documentation changes are now live, with a very clear and explicit distinction between the usage syntax for projects and plugins.

**Comment by jonpas** [comment]
Looks great! Thanks!

**Pull request merged**
